### PR TITLE
Add basic documentation of font and type scale

### PR DESCRIPTION
**Pull request by hamishtaplin**
Screenshot 2021-02-23 at 13 28 36

### What

- added some docs for font and type scale usage
- added ONS logo to header
- added Open Sans as the font used in the doc site itself
- created collection for "styles" and implemented in navigation
- moved responsibility for page title into main layout.njk

### How to review

- check the content makes sense
- review code

### Who can review

Anyone

### CODE REVIEW

**Review by armstrongb — COMMENTED** [review]
Font weight set to 700 now. lgtm.

**Review by armstrongb — CHANGES_REQUESTED** [review]
Looks like the changes to `700` have been made but there are problems with the netlify preview as it is throwing a `404` for `_typography.scss` and is displaying as regular.

Screenshot 2021-02-26 at 13 45 11

**Comment by hamishtaplin** [comment]
> Looks like the changes to `700` have been made but there are problems with the netlify preview as it is throwing a `404` for `_typography.scss` and is displaying as regular.
> 
> Screenshot 2021-02-26 at 13 45 11

Weird cos I have seen this but it's not doing it right now, will investigate.

**Comment by hamishtaplin** [comment]
> Looks like the changes to `700` have been made but there are problems with the netlify preview as it is throwing a `404` for `_typography.scss` and is displaying as regular.

Works in Safari but not Chrome, will investigate

**Comment by hamishtaplin** [comment]
Having investigated the bold issue, it appears to be a conflict with the locally-installed version of Open Sans. Seeing a we both saw this then it's worth sorting out.

**Comment by hamishtaplin** [comment]
So the problem was with the `local` reference in our `font-face` declaration — I've removed this for now along with the unnecessary embedding from Google Fonts

**Review by armstrongb — APPROVED** [review]
LGTM with the 700/600 and font loading resolved.

**Pull request merged**
