### PR TITLE
Addition of tints for reference

### PR DESCRIPTION
**Pull request by armstrongb**
### What

Added tints output as hex values to the colours documentation page.

### How to review

Check that the output is displayed as expected.
Review the implementation to generate the output.

### Who can review

Anyone.

### CODE REVIEW

**Comment by hamishtaplin** [comment]
I'm not sure how useful this is as:

- it gives the impression that there are variables (eg. `$ruby-red-70`) available in Sass which don't exist.
- it adds a lot of content to the page which isn't particularly useful beyond seeing the colours

If we're going to do this then it needs to accurately document code the user can use right now. I would also make each tint a child of the main colour to give it some hierarchy—there's more of the page dedicated to tints than there is the colours themselves

**Comment by will-madebymoon** [comment]
I think this is dangerous as it's suggesting these are legimate colours.

**Comment by armstrongb** [comment]
Happy to make this a child of colours and change up the naming for them too to 'non sass variable sounding' things. If this is going to be any more than a website component library we're going to need to account for tints though.

**Comment by Rachel-Price-ONS** [comment]
Agree the tints are quite prominent on the page and not sure if we need them listed out. Do we need hex values if they will be used by modifying the colours? Happy to keep the text until "General palette tints" header, but maybe take the displayed colours off. Keep the list of hex values somewhere else in case there is a need for them in future.

**Comment by armstrongb** [comment]
Cool. Will close this PR and we'll resurrect on if print finds it necessary.

**Pull request closed without merging**
